### ISSUE TITLE
Logging out invalidates ApplozicClient objects

### ISSUE THREAD

**Issue by jksk** [AppLozic/Applozic-Chat-iOS-Framework#108]
Logging out clears NSUserDefaults, including where the application key is stored. This means any subsequent usage of the ApplozicClient fails.

**Comment by Sunilkumarr** [comment]
@jksk We will think about not clear appllicationKey. 

Another way is you can set up the application key once logout is a success again using the     

     self.applozicClient = [[ApplozicClient alloc ]initWithApplicationKey:@"applozic-sample-app"]; //Pass App ID here 

Setup application key Docs link: https://docs.applozic.com/docs/ios-chat-session#section-setup-application
