### ISSUE TITLE
Completion block not called

### ISSUE THREAD

**Issue by jksk** [AppLozic/Applozic-Chat-iOS-Framework#109]
https://github.com/AppLozic/Applozic-Chat-iOS-Framework/blob/master/Applozic/ALChannelClientService.m#L71

If the application reaches the above state, the completion block is not called.

**Comment by Sunilkumarr** [comment]
@jksk We will add a competition block in one of our releases and let you know.

**Comment by Sunilkumarr** [comment]
@jksk You can use the latest version of Applozic v 7.0.0 this issue is fixed in that.
