### ISSUE TITLE
ALConstant.h contains commonly used words

### ISSUE THREAD

**Issue by jksk** [AppLozic/Applozic-Chat-iOS-Framework#110]
Since this is a framework, and Objective-C isn't namespaced, it's probably a good idea to use prefixes on e.g. #define directives and C enums. There might be collisions with other vendors and the apps themselves. E.g. we just integrated Applozic, and had to make some changes since this framework defines `BETA` as an enum value.

**Comment by Sunilkumarr** [comment]
@jksk You can use the latest version of Applozic 7.0.0 we have added Prefix in our Constants and enum
