### ISSUE TITLE
Crash while opening app from notification in ALMessageDBService

### ISSUE THREAD

**Issue by iamabhiee** [AppLozic/Applozic-Chat-iOS-Framework#119]
Getting crash while opening app from notification, attaching crash log from the apple

https://prnt.sc/tayzco

**Comment by mukeshthawani** [comment]
Thanks for sharing the details. This will be fixed in the upcoming version which will be released by Monday EOD.

**Comment by Sunilkumarr** [comment]
@iamabhiee This as fixed in our latest versions You can use the latest version [link](https://docs.applozic.com/docs/ios-chat-sdk#automated-installation-using-cocoapods)
