### ISSUE TITLE
Unable to fetch contacts

### ISSUE THREAD

**Issue by kunass2** [AppLozic/Applozic-Chat-iOS-Framework#18]
All I do in my controller is:
<pre>
class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let user = ALUser();
        user.applicationId = ALChatManager.applicationId
        user.userId = "1234"
        user.email = "h@h.pl"
        user.password = "password"
        user.displayName = "DemoUserName"
        
        ALUserDefaultsHandler.setUserId("1234")
        ALUserDefaultsHandler.setEmailId("h@h.pl")
        ALUserDefaultsHandler.setDisplayName("supernemo fighter")
        ALUserDefaultsHandler.setApplicationKey("railwaymen12e52e053b4aa8bf157aa77c2f4dfbdad")
        
        let manager = ALChatManager(applicationKey: "railwaymen12e52e053b4aa8bf157aa77c2f4dfbdad")
        manager.registerUserAndLaunchChat(user, fromController: self, forUser: nil)
    }
}
</pre>

And when I try to display contacts, the result is empty... but it shouldn't.

On console I get the response

>2016-12-14 13:28:00.651004 Chat[511:99388] GET_URL :: https://apps.applozic.com/rest/ws/user/filter?pageSize=100
2016-12-14 13:28:00.651707 Chat[511:99388] Basic string...Basic MTIzNDoobnVsbCk=
2016-12-14 13:28:00.873666 Chat[511:99388] ERROR_RESPONSE : Error Domain=NSURLErrorDomain Code=-1012 "(null)" UserInfo={NSErrorFailingURLStringKey=https://apps.applozic.com/rest/ws/user/filter?pageSize=100, NSUnderlyingError=0x174250e00 {Error Domain=kCFErrorDomainCFNetwork Code=-1012 "(null)" UserInfo={_kCFURLErrorAuthFailedResponseKey=<CFURLResponse 0x1700f0580 [0x1aae24bb8]>{url = https://apps.applozic.com/rest/ws/user/filter?pageSize=100}}}, NSErrorFailingURLKey=https://apps.applozic.com/rest/ws/user/filter?pageSize=100} && ERROR:CODE : -1012
2016-12-14 13:28:00.873843 Chat[511:99388] HTTP:401 : ERROR CODE : -1012
2016-12-14 13:28:00.874448 Chat[511:99388] ERROR_IN_FETCH_CONTACT_WITH_PAGE_SIZE : Error Domain=Applozic Code=1 "Unable to connect with the server. Check your internet connection and try again" UserInfo={NSLocalizedDescription=Unable to connect with the server. Check your internet connection and try again}
2016-12-14 13:28:00.877150 Chat[511:99388] NO ENTRY FOUND

What is wrong with this?

**Comment by Abhishek9634** [comment]
@kunass2 : can you  comment this line and try 
user.applicationId = ALChatManager.applicationId

**Comment by kunass2** [comment]
It still doesnt work. Before registering `ALChatManager` I try to create contact:

        let contact = ALContact()
        contact.userId = "1"
        contact.fullName = "hello"
        contact.email = "w@w.pl"
        contact.displayName = "Adarsh"
        
        ALContactService().add(contact)

but it still displays: "unable to fetch contacts". Why?

**Comment by Abhishek9634** [comment]
@kunass2 : can you share complete logs from login to to contact error response and if possible can you share your dmo project in which you integrate our SDK?

**Comment by kunass2** [comment]
demo is here: https://github.com/kunass2/applozicdemo

**Comment by kunass2** [comment]
I think I made a mistake with user and password. Now it seems to work

**Comment by Abhishek9634** [comment]
let user = ALUser();
        user.applicationId = ALChatManager.applicationId
        user.userId = "1234"
        user.email = "h@h.pl"
        user.password = "password"
        user.displayName = "DemoUserName"
        
        
        let contact = ALContact()
        contact.userId = "1"
        contact.fullName = "hello"
        contact.email = "w@w.pl"
        contact.displayName = "Adarsh"
        
        ALContactService().add(contact)
        
        ALUserDefaultsHandler.setUserId(user.userId)
        ALUserDefaultsHandler.setEmailId(user.email)
        ALUserDefaultsHandler.setPassword(user.password)
        ALUserDefaultsHandler.setDisplayName(user.displayName)
        ALUserDefaultsHandler.setApplicationKey("railwaymen12e52e053b4aa8bf157aa77c2f4dfbdad")
        
        let manager = ALChatManager(applicationKey: "railwaymen12e52e053b4aa8bf157aa77c2f4dfbdad")
        manager.registerUser(user) { (response, error) in
            
            manager.registerUserAndLaunchChat(user, fromController: self, forUser: nil)
        }

**Comment by kunass2** [comment]
thank you. Everything is fine now.
