### ISSUE TITLE
Getting a full list of contacts, that do not exist on my application.

### ISSUE THREAD

**Issue by adamsrosco** [AppLozic/Applozic-Chat-iOS-Framework#25]
Hi,

When using the demo app using my application ID, when selecting the contacts screen, I am getting users returned which do not exist on my application. My application users do come back in that list, but where i am expecting about 8 users, I am receiving about 40+.

The setFilterContactsStatus is set to TRUE, but this does not seem to make a difference.

![simulator screen shot 05 may 2017 09 27 05](https://cloud.githubusercontent.com/assets/2970598/25736903/0c3ae242-3175-11e7-9e2c-31a564072e72.png)

![simulator screen shot 05 may 2017 09 26 57](https://cloud.githubusercontent.com/assets/2970598/25736904/0c3c2148-3175-11e7-8dd7-67eec27f71f9.png)

**Comment by adarshmishra** [comment]
hello @adamsrosco 
Can you please check, if those unwanted users you can see on your Applozic dashboard ? For demo purpose sample app have codes which will insert contacts manually. You can check below code and comment it out if present.
```
        [self insertInitialContacts];
```

**Comment by adamsrosco** [comment]
Hi, 

Was not inserting any demo contacts. I have re run the project and the list is bringing back my contacts as expected.

Thanks.

**Comment by adamsrosco** [comment]
Hi,

Please see issue 386... there seems to be a bug in the framework where the filterContactType is not being checked when scrolling the contacts table view. It refreshes with a full list of registered contacts.
