### ISSUE TITLE
Non-portable path to file DB_Contact.h

### ISSUE THREAD

**Issue by facconi** [AppLozic/Applozic-Chat-iOS-Framework#37]
Xcode 9 reports the following error:

    Non-portable path to file '"DB_CONTACT.h"'; specified path differs in case from file name on disk

It gives the following suggestion to remove the warning:

    Replace '"DB_Contact.h"' with '"DB_CONTACT.h"'

**Comment by mukeshthawani** [comment]
This is a warning, not an error. You can build and run the project without any issues. We will fix it in the future release.

Thanks for reporting.

**Comment by mukeshthawani** [comment]
This should be working fine in the latest version.
