### ISSUE TITLE
'CNContact' is partial: introduced in iOS 9.0 in ALVCardClass.h

### ISSUE THREAD

**Issue by facconi** [AppLozic/Applozic-Chat-iOS-Framework#38]
In file ALVCardClass.h Xcode reports two errors:

    'CNContact' is partial: introduced in iOS 9.0

**Comment by mukeshthawani** [comment]
This is a warning, not an error. You can build and run the project without any issues. We will fix it in the future release.

Thanks for reporting.

**Comment by facconi** [comment]
Thank you! I was just debugging my app and found this.
