### ISSUE TITLE
Error on the forked repo

### ISSUE THREAD

**Issue by malavikaanup** [AppLozic/Applozic-Chat-iOS-Framework#43]
I am using Applozic via cocoapods. As I need to make some changes, I forked this repo and cloned. But when built with generic device, it is showing errors.

1.  Include of non-modular header inside framework module 'Applozic': '/Users/malavika/Documents/Emvigo/Applozic-Chat-iOS-Framework/Applozic/ALGroupUser.h'

2. Could not build Objective-C module 'Applozic'.

<img width="1280" alt="screen shot 2018-06-08 at 5 22 01 pm" src="https://user-images.githubusercontent.com/23278107/41156731-cb84524a-6b40-11e8-87dc-6f6f65742762.png">

I have attached a screenshot of it.
Please help as the work is a bit urgent.

Thanks in Advance

**Comment by mukeshthawani** [comment]
When you use it from your app then it should work fine, building the framework alone might fail.

**Comment by malavikaanup** [comment]
I need to make few changes in the Applozic code. When there is error, the change is not reflecting on the pod url I use.
