### ISSUE TITLE
Is there a real time updates for iOS ?

### ISSUE THREAD

**Issue by Sander-Kornev** [AppLozic/Applozic-Chat-iOS-Framework#49]
I can see that there is an article for Android and not for iOS regarding real-time updates.
https://docs.applozic.com/docs/mobile-real-time-update

Is there anything similar for iOS? Or is it going to be developed in the nearest future?

**Comment by mukeshthawani** [comment]
The doc link that you shared should be used when you are developing your own UI from scratch using our APIs. Which we will release very soon for iOS.
But if are using our UI then do the notification setup as described here: https://docs.applozic.com/docs/ios-push-notification and you will receive the real-time updates.

**Comment by Sander-Kornev** [comment]
Thanks. Yes, we are using your ALChatViewController with our own controller for chat list.
The disadvantage of the mentioned approach with push notifications for our case is that user might not allow push notifications for our app. In that case we are unable to receive updates like it would be with some socket API or public observers API from the SDK.

**Comment by mukeshthawani** [comment]
Thanks for sharing the details @Sander-Kornev. We will release the new APIs and documentation by the end of this week.
