### ISSUE TITLE
[Skylab] get current muted status of ALContact

### ISSUE THREAD

**Issue by Yuri-Kuchinskiy** [AppLozic/Applozic-Chat-iOS-Framework#55]

**Comment by Sander-Kornev** [comment]
How can we check that ALContact is muted?
For instance, we have -(BOOL) isNotificationMuted; for ALChannel. But what about ALContact?

**Comment by Sunilkumarr** [comment]
@Sander-Kornev  currently this feature we don't have we will add in our upcoming releases

**Comment by Sander-Kornev** [comment]
@Sunilkumarr Did you add this feature?

**Comment by Sunilkumarr** [comment]
@Sander-Kornev Working on this feature will add in our upcoming releases

**Comment by Sander-Kornev** [comment]
@Yuri-Kuchinskiy  It seems that we can close this one. It works in 6.3.0
