### ISSUE TITLE
[Skylab] Inability to use dynamic fonts in ALChatViewController's UITableViewCells

### ISSUE THREAD

**Issue by Sander-Kornev** [AppLozic/Applozic-Chat-iOS-Framework#56]
Now they are created in the way that doesn't allow using dynamic fonts. All the calculations are done manually with the following method 

```
- (CGRect)boundingRectWithSize:(CGSize)size options:(NSStringDrawingOptions)options attributes:(nullable NSDictionary<NSAttributedStringKey, id> *)attributes context:(nullable NSStringDrawingContext *)context
```
and moreover font sizes are added as constants and hardcoded, for example **MESSAGE_TEXT_SIZE**

```
+(CGSize)textSize:(ALMessage *)theMessage andCellFrame:(CGRect)cellFrame
{
    CGSize theTextSize = [ALUtilityClass getSizeForText:theMessage.message
                                               maxWidth:cellFrame.size.width - 115
                                                   font:[ALApplozicSettings getFontFace]
                                               fontSize:MESSAGE_TEXT_SIZE];
    
    return theTextSize;
}
```
What can be done with it?
Do you consider going with autolayouts?

**Comment by Sunilkumarr** [comment]
We don’t have any plan to use autolayout. We might fix it by considering dynamic font while calculating size. You can also create a PR if you have any idea.

**Comment by Sander-Kornev** [comment]
@Sunilkumarr  It's interesting that it was promised a year ago https://github.com/AppLozic/Applozic-iOS-SDK/issues/378

**Comment by Sunilkumarr** [comment]
@Sander-Kornev I know we were working on it and we tried.

Performance wise Autolayout is not the best solution. You can check the benchmark here: https://github.com/layoutBox/LayoutFrameworkBenchmark

We will update you once we have more to share. Thanks for sharing the details.

**Comment by Sander-Kornev** [comment]
Hope with iOS 12 release it would no longer be an issue

**Comment by Sander-Kornev** [comment]
@Sunilkumarr  Is it possible, as a temporary solution to add some external configuration to specify font sizes that were changed in https://github.com/AppLozic/Applozic-iOS-SDK/pull/491 ?
Let them be static as for now but just to be able to configure them from outside from ALApplozicSettings

**Comment by Sander-Kornev** [comment]
@Sunilkumarr Any update on this?

**Comment by Sunilkumarr** [comment]
@Sander-Kornev we will add setting in this updated

**Comment by Sunilkumarr** [comment]
@Sander-Kornev You can use the latest version 6.3.0 settings are added for font size 

       [ALApplozicSettings setChatCellTextFontSize:15];
       [ALApplozicSettings setChannelCellTextFontSize:15];
