### ISSUE TITLE
[Skylab] Real-time update issue on sending a message

### ISSUE THREAD

**Issue by Sander-Kornev** [AppLozic/Applozic-Chat-iOS-Framework#57]
We have the following Setup
Custom ChatListViewController -> Applozic's ALChatViewController
The functionality of ChatListViewController is based on real-time updates.

User goes to SDK's ALChatViewController, sends some messages, goes back to "Custom ChatListViewController" and at that moment chat information is outdated. iOS app didn't receive any real-time updates, that user have sent messages.
Android receives next callback
` public void onMessageSent(Message message)`

iOS doesn't receive 
`-(void) onMessageSent:(ALMessage *) alMessage;`

**Comment by Sunilkumarr** [comment]
@Sander-Kornev  Will add in our next release on Tuesday will merge this change as it as suggested changes for onMessageSent callback  and other changes https://github.com/AppLozic/Applozic-iOS-SDK/pull/488
