### ISSUE TITLE
[Skylab] no Warnig Toast if Video or file is large then allowed limit

### ISSUE THREAD

**Issue by Yuri-Kuchinskiy** [AppLozic/Applozic-Chat-iOS-Framework#60]
When selecting File or Video large then allowed limit, there is no warning toast on UI about the error. Android works as expected shows the warning toast.

**Comment by Sunilkumarr** [comment]
Will add waring toast in one of the future releases, will try to release it in next 15 days.

**Comment by Sander-Kornev** [comment]
@Sunilkumarr Actually, there is a problem with async session export. The user might press "Done" button before AVAssetExportSession finishes its async export. We are thinking about creating pull request and get back to you in this case shortly.

**Comment by Yuri-Kuchinskiy** [comment]
@Sander-Kornev we will need to use the OSD for the case of video transcoding, with message:
Optimizing Videos, see ticket: https://skylabusa.atlassian.net/browse/C20-215

**Comment by Sander-Kornev** [comment]
@Sunilkumarr I've added new commit to pull request https://github.com/AppLozic/Applozic-iOS-SDK/pull/488

**Comment by Sander-Kornev** [comment]
@Yuri-Kuchinskiy @Sunilkumarr 
Please close the ticket since it was merged.
