### ISSUE TITLE
[Skylab] Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by Sander-Kornev** [AppLozic/Applozic-Chat-iOS-Framework#63]
I get this crash while uploading/downloading large video files.
There are several reasons:

1. Usage of outdated NSURLConnection. Please use NSURLSession instead with its download and upload tasks. It will prevent reading/saving whole file into a variable like 
```
NSData *imageData = [[NSData alloc]initWithContentsOfFile:filePath]; <ALMessageService.m:680>
```

2. Retrieving the length of the file by loading it into a variable. There is a method of NSFileManager https://developer.apple.com/documentation/foundation/nsfilemanager/1410452-attributesofitematpath?language=objc

**Comment by Sunilkumarr** [comment]
Hi, We will look into it and will fix it

**Comment by Sander-Kornev** [comment]
@Sunilkumarr  It seems that with the decoding the issue isn't topical anymore
