### ISSUE TITLE
[Skylab] Selectin Video from Gallery Issue

### ISSUE THREAD

**Issue by Yuri-Kuchinskiy** [AppLozic/Applozic-Chat-iOS-Framework#65]
There is no ability to select long video from Gallery and have sdk to transcode it to 480p for sending via the wire

**Comment by Sander-Kornev** [comment]
@mukeshthawani added pull request https://github.com/AppLozic/Applozic-iOS-SDK/pull/492
Please, take a look

**Comment by Yuri-Kuchinskiy** [comment]
Fixed in 6.3.0 release
