### ISSUE TITLE
[Skylab] ALUserService's getTotalUnreadCount stuck with some outdated data. Relogin helps. (C20-260)

### ISSUE THREAD

**Issue by Sander-Kornev** [AppLozic/Applozic-Chat-iOS-Framework#67]
sent details as the attached file in an email

**Comment by Sunilkumarr** [comment]
On success of group conversation thread delete you can reset the unread count to zero using below method     

For group chat : ``` [ALChannelService setUnreadCountZeroForGroupID:channelKey]; ```

For one to one chat :   ```  [ALUserService setUnreadCountZeroForContactId:userId]; ```

**Comment by Sander-Kornev** [comment]
@Sunilkumarr 
Can you do it inside SDK?

**Comment by Sander-Kornev** [comment]
@Sunilkumarr for example when a user deletes the history

**Comment by Sunilkumarr** [comment]
@Sander-Kornev  
We will have to work on a release to add the said method into our SDK that would take time, to speed up the process please add the above method on the conversation thread to reset the count in the local DB.

Also, I was not able to understand 
"for example when a user deletes the history"

The above method would help you reset the local DB and the unread count when a user/admin deletes a group. Is there anything more you want to do post that?

**Comment by Sander-Kornev** [comment]
@Sunilkumarr  the set up is following

We have a channel. The user receives messages, the channel is unread.
Then our server makes following request to Applozic using this request https://apps.applozic.com/rest/ws/group/delete ( link to docs https://docs.applozic.com/v1.0/reference#group-delete ).

According to your suggestion in https://github.com/AppLozic/Applozic-Chat-iOS-Framework/issues/61 our API server sends following request to delete the conversation for each user /rest/ws/message/delete/conversation?groupId={}&ofUserId={}

And according to my attached logs, iOS app receives 
-(void) onConversationDelete:(NSString *) userId withGroupId: (NSNumber*) groupId;
callback but unread count remains, again according to the logs.

So I agree, that as a temporary workaround we can add suggested method 

```
For group chat : [ALChannelService setUnreadCountZeroForGroupID:channelKey];
For one to one chat : [ALUserService setUnreadCountZeroForContactId:userId];
```

inside `onConversationDelete` callback until you will be able to add these calls to remove unread count into your SDK. But I believe that it's SDK's responsibility to clear Unread count for such channels.

Besides mentioned workaround might not work in the case when user's app is closed when onConversationDelete message is sent.

**Comment by Sunilkumarr** [comment]
@Sander-Kornev Thanks for deatils , 

Got it I thought you where deleting conversation thread from IOS device after getting delete group notification . 
 Will add those method in our Sdk  on upcoming release.

**Comment by Sunilkumarr** [comment]
@Sander-Kornev You can use our latest SDK to check we have added method to reset count in case off delete

**Comment by Sander-Kornev** [comment]
@Sunilkumarr  We still can reproduce the issue. I sent you the logs via email. Please, reopen the ticket.
