### ISSUE TITLE
[Skylab]  Chat Screen: for some users the display of contact's «Last seen on... » is not accurate

### ISSUE THREAD

**Issue by Sander-Kornev** [AppLozic/Applozic-Chat-iOS-Framework#70]
We've received the following request from our customers
"On some cases, the «Last seen...» time of a contact is not accurate—it's saying that the user hasn't been active for a long time, when the case is that the user has been recently or currently active."

![screenshot_10_1_18__11_24_pm](https://user-images.githubusercontent.com/3295273/46339354-3aff9a80-c63b-11e8-8bef-6e7e37d775dd.jpg)

Name is hidden intentionally

**Comment by Sunilkumarr** [comment]
@Sander-Kornev can you share us the applicationKey and  login userId and password of one user where this issue is coming to support@applozic.com
