### ISSUE TITLE
LaunchIndividualChat with conversationId crash!!!

### ISSUE THREAD

**Issue by acpnayak** [AppLozic/Applozic-Chat-iOS-Framework#77]
When I call below function:
-(void)launchIndividualChat:(NSString *)userId withGroupId:(NSNumber*)groupID withConversationId:(NSNumber *)conversationId
    andViewControllerObject:(UIViewController *)viewController andWithText:(NSString *)text

App crashes.

Below is stacktrace:
2018-12-26 18:45:53.835124+0530 EvalExpert[10716:169196] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001101b81bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010f5d7735 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001101b8015 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010c3a1eb4 +[NSJSONSerialization JSONObjectWithData:options:error:] + 67
	4   Applozic                            0x0000000109e264bf -[ALConversationProxy getTopicDetail] + 159
	5   Applozic                            0x0000000109de50db -[ALChatViewController getHeaderView] + 555
	6   Applozic                            0x0000000109de3f85 -[ALChatViewController tableView:heightForHeaderInSection:] + 341
	7   UIKitCore                           0x000000011629baa1 -[UITableView _delegateWantsHeaderForSection:] + 220
	8   UIKitCore                           0x00000001162c7099 -[UISectionRowData refreshWithSection:tableView:tableViewRowData:] + 160
	9   UIKitCore                           0x00000001162cbf62 -[UITableViewRowData numberOfRows] + 95
	10  UIKitCore                           0x0000000116282cc9 -[UITableView noteNumberOfRowsChanged] + 117
	11  UIKitCore                           0x0000000116282225 -[UITableView reloadData] + 1529
	12  Applozic                            0x0000000109de9fde -[ALChatViewController loadChatView] + 2590
	13  Applozic                            0x0000000109dcf720 -[ALChatViewController viewDidLoad] + 304
	14  UIKitCore                           0x0000000115a454e1 -[UIViewController loadViewIfRequired] + 1186
	15  UIKitCore                           0x0000000115a45940 -[UIViewController view] + 27
	16  UIKitCore                           0x00000001159b3177 -[UINavigationController preferredContentSize] + 197
	17  UIKitCore                           0x00000001159640ec -[UIPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 64
	18  UIKitCore                           0x000000011595fd0b __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 116
	19  UIKitCore                           0x00000001160700d2 _runAfterCACommitDeferredBlocks + 318
	20  UIKitCore                           0x000000011605eb2c _cleanUpAfterCAFlushAndRunDeferredBlocks + 384
	21  UIKitCore                           0x000000011608defc _afterCACommitHandler + 135
	22  CoreFoundation                      0x000000011011cc27 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	23  CoreFoundation                      0x00000001101170be __CFRunLoopDoObservers + 430
	24  CoreFoundation                      0x0000000110117751 __CFRunLoopRun + 1537
	25  CoreFoundation                      0x0000000110116e11 CFRunLoopRunSpecific + 625
	26  GraphicsServices                    0x00000001148c61dd GSEventRunModal + 62
	27  UIKitCore                           0x000000011606481d UIApplicationMain + 140
	28  EvalExpert                          0x0000000106264d90 main + 112
	29  libdyld.dylib                       0x0000000111591575 start + 1
	30  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by adamsrosco** [comment]
I am getting this same issue. Did you manage to find resolution?

**Comment by adamsrosco** [comment]
Initial investigations seem to point to the TopicDetailID being nil. When the getTopicDetail call tries to serialize the JSON, because the objectData is nil, the crash occurs. This is an old chat account, AL investigated and some of the fields of the chat were reset... Warrants further investigations. Does not happen on any of the other chat users.

**Comment by ShivamPokhriyal** [comment]
Fixed in version 6.8.1
