### ISSUE TITLE
Crash on AlMessageService

### ISSUE THREAD

**Issue by roula-mis** [AppLozic/Applozic-Chat-iOS-Framework#81]
The library crashes when I first open the chat screen directly after group creation. on ALMessageService.m Line 454 (when the code attempts to hide the message of 'User created the group')

When I open the chat a second time using its ID everything goes fine.

<img width="1280" alt="screenshot 2019-01-13 at 12 15 06" src="https://user-images.githubusercontent.com/45661530/51084648-b2aa8e80-172d-11e9-8fc4-61a366f64c7d.png">

**Comment by Sunilkumarr** [comment]
This as been fixed  the latest version  6.7.1    
   ```
 use_frameworks!
pod 'Applozic', '~> 6.7.1'

```
