### ISSUE TITLE
No interface to get the unread messages for Contextual Conversation

### ISSUE THREAD

**Issue by acpnayak** [AppLozic/Applozic-Chat-iOS-Framework#89]
Hi, We have implemented the Contextual Conversation in one of our application. But we facing some issues with Contextual Conversations highlighted below

#1. We can't find any interface to get unread message count for Contextual conversation
#2. When user A is not in the Contextual Conversation window, and other user B send some messages in Conversation (say user B sent 3 new messages), and now user A launch the Contextual conversation window, user A is not shown new messages (received when he was not in window). And now if user B send new messages with user A in chat window, he will receive other 3 messages as well.

Please look into the above issues and let us know if you need more information.

Thanks.

**Comment by Sunilkumarr** [comment]
@acpnayak Hello,

1)We can't find any interface to get unread message count for Contextual conversation
-->If any unread messages are in  any context conversation it will show in the conversation list screen 
if you're looking for an unread count method which you want to show on your UI screen  you can check this [link ](https://docs.applozic.com/docs/ios-unread-count#section-individual-user)
**Note:**This will give overall unread conversation count with user  

2)When user A is not in the Contextual Conversation window, and other user B send some messages in Conversation (say user B sent 3 new messages), and now user A launch the Contextual conversation window, user A is not shown new messages (received when he was not in window). And now if user B send new messages with user A in chat window, he will receive other 3 messages as well.

-->There is some issue in push notification  setup. You can send us your applicationKey and one login userId to support@applozic.com

**Comment by acpnayak** [comment]
Hi Sunil: Thanks for swift response. 

We not showing the Conversation List to user.
In our app we have different evaluations, and for each evaluation we create Contextual conversation. So we need interface to have unread count for each conversation without showing the list.

I have already gone through above Interfaces of unread count, but couldn't find the one we looking for.

**Comment by Sunilkumarr** [comment]
@acpnayak Can you explain more about Interfaces means?

**Comment by acpnayak** [comment]
@Sunil with the interface I mean some function to get the unread count for one to one user but specific to topic

**Comment by acpnayak** [comment]
@Sunil: Let me know if there is any update, if you need more information pls do let us know!

**Comment by acpnayak** [comment]
@Sunilkumarr Let me know if there is any update, if you need more information pls do let us know!

**Comment by Sunilkumarr** [comment]
@acpnayak Currntly we dont have support for the unread count for one to one user but specific to the topic in Context-based chat.

There is another way to achieve this using  group of two based. It will be the same as one to one chat and each topic will have different thread conversation  we will send you instruction on how to create a group of two with context-based chat

**Comment by acpnayak** [comment]
hmm, Ok send us the instructions for creating group of two with context-based chat.

Will it have the same kind of headers? and also it will add another user automatically to chat right?

**Comment by isaacrojasgarcia** [comment]
Following up.

**Comment by Sunilkumarr** [comment]
@acpnayak  @isaacrojasgarcia Hi you can check this doc link for creating group of two [link](https://docs.applozic.com/v1.0/docs/ios-group-chat-sdk#section-context-based-chat-in-a-group-of-two)

**Comment by acpnayak** [comment]
Hi @Sunilkumarr: Thanks let us just check with that, if that solve our problem!

**Comment by acpnayak** [comment]
Hi @Sunilkumarr: We couldn't find any similar option to in Android creating group of two with context based chat. Can you confirm?

**Comment by Sunilkumarr** [comment]
@acpnayak You can check this doc for android : [link](https://docs.applozic.com/v1.0/docs/android-group-chat-sdk#section-context-based-chat-in-a-group-of-two)
