### ISSUE TITLE
[Skylab] Audio can't be downloaded immediately

### ISSUE THREAD

**Issue by Sander-Kornev** [AppLozic/Applozic-Chat-iOS-Framework#95]
We found an issue when one user records audio and sends it to another user. In case the second user is on One to One chat screen, the audio file is retrieved, but it can't be downloaded and listened to. The only way is to exit the Conversation screen and open it again. In this case, user will be able to download the audio and listen to it.

![IMG_27ED27234FB8-1](https://user-images.githubusercontent.com/3295273/58166855-63540c00-7c93-11e9-97c9-52f3a6c982d0.jpeg)

**Comment by Sunilkumarr** [comment]
@Sander-Kornev We have fixed audio download button not showing in  latest version  ``` pod 'Applozic', '~> 6.10.0' ```

**Comment by Sander-Kornev** [comment]
@Sunilkumarr seems it works fine. Thanks
